### ISSUE TITLE
Command to create award JSON

### ISSUE THREAD

**Issue by MarkHerhold** [BadgeUp/sponge-client#25]
It's very difficult to figure out the JSON required to create an award, especially if it's modded.

Ideally we could have a command `/badgeup awardthis` which would serialize the item in the player's hand and create a link to the dashboard with the JSON data in a query parameter, e.g. `https://dashboard.badgeup.io/#/awards/create?json={}`.

**Comment by Mohron** [comment]
That would be a good idea! I would ask that you make a seperate /badgeup award add item and /badgeup award add inventory since a single award could a one item or a set of items that an admin could gather in there invetory before creating. You could also have a /badgeup award add command <command without preceding slash>.

**Comment by RobertHerhold** [comment]
@Mohron Multiple different items would be multiple different BadgeUp awards, so I don't think that would be necessary. Good idea though!

**Comment by Mohron** [comment]
Well then just item and command.

Edit: I guess since it's json, I figured you could get away with adding an array of items...

**Comment by Mohron** [comment]
I guess since it's json, I figure you could get away with adding an array of items...

**Comment by RobertHerhold** [comment]
![create award function](https://media.giphy.com/media/3o7bu88jz8ymR1NbTq/giphy.gif "`/badgeup awards create inhand` command")
